// 编写人：Aurora
// 主题预设数据。挂载到 window.AdminApp.theme
'use strict';

(function () {
const defaultThemeLook = {
  themePrimary: '#ff6f91',
  themeAccent: '#21b6a8',
  themeText: '#ffffff',
  themeBackground: '#181823',
  queueSongFontSize: '40',
  queueTitleFontSize: '30',
  themeOpacity: '0.35',
  themeRadius: '12',
  overlayLowPowerMode: 'false',
  backdropBlur: '0',
  glowIntensity: '0',
  enableGradient: 'false',
  gradientEnd: '#181823',
  gradientAngle: '135',
  overlayFontFamily: 'Microsoft YaHei',
  overlayFontWeight: '800',
  overlaySongColor: '',
  overlayRequesterColor: '',
  overlayTitle: '',
  overlayShowIndex: 'true',
  overlayIndexThreshold: '0',
  overlayIndexColor: '#fbbf24',
  queueFixedSixRows: 'true',
  queueScrollMode: 'bounce',
  queueScrollSpeed: '80',
  // 新增参数 - 排版
  lineHeight: '1.4',
  letterSpacing: '0',
  textShadowIntensity: '0',
  // 新增参数 - 阴影与边框
  cardShadow: 'light',
  cardShadowColor: '#000000',
  shadowOpacity: '0.15',
  cardBorderWidth: '0',
  cardBorderColor: '',
  panelBorderWidth: '1',
  panelBorderColor: 'rgba(255,255,255,0.1)',
  // 新增参数 - 间距
  itemSpacing: '8',
  rowSpacing: '5',
  panelPadding: '14'
};

const classicThemePresets = {
  // === 极简（纯透背景）- 重点优化 ===
  pure: {
    themePrimary: '#555555', themeAccent: '#888888',
    themeText: '#1a1a1a', themeBackground: '#ffffff',
    themeOpacity: '0.00', themeRadius: '0',
    backdropBlur: '0', glowIntensity: '0',
    enableGradient: 'false', gradientEnd: '#ffffff', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '600',
    overlaySongColor: '#1a1a1a',
    overlayRequesterColor: '#666666',
    queueScrollSpeed: '80',
    // 极简风格的新参数
    lineHeight: '1.5',
    letterSpacing: '0.5',
    textShadowIntensity: '0',
    cardShadow: 'none',
    cardShadowColor: '#000000',
    shadowOpacity: '0',
    cardBorderWidth: '1',
    cardBorderColor: 'rgba(0,0,0,0.08)',
    panelBorderWidth: '0',
    panelBorderColor: '',
    itemSpacing: '12',
    rowSpacing: '6',
    panelPadding: '16'
  },
  // === 浅色系（明亮白透毛玻璃） ===
  cream: {
    themePrimary: '#f59e0b', themeAccent: '#d97706',
    themeText: '#2d1a08', themeBackground: '#f5ede4',
    themeOpacity: '0.45', themeRadius: '14',
    backdropBlur: '24', glowIntensity: '2',
    enableGradient: 'true', gradientEnd: '#e8d5c0', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'KaiTi, STKaiti, serif',
    overlayFontWeight: '700',
    overlaySongColor: '#5c3d1a',
    overlayRequesterColor: '#8b6914',
    queueScrollSpeed: '80',
    lineHeight: '1.5', letterSpacing: '0', textShadowIntensity: '1',
    cardShadow: 'medium', cardShadowColor: '#d97706', shadowOpacity: '0.12',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(217,119,6,0.15)',
    itemSpacing: '10', rowSpacing: '5', panelPadding: '14'
  },
  sky: {
    themePrimary: '#3b82f6', themeAccent: '#f59e0b',
    themeText: '#1a2e3d', themeBackground: '#e8f2f8',
    themeOpacity: '0.42', themeRadius: '12',
    backdropBlur: '22', glowIntensity: '2',
    enableGradient: 'true', gradientEnd: '#d8e8f4', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '700',
    overlaySongColor: '#1e40af',
    overlayRequesterColor: '#64748b',
    queueScrollSpeed: '80',
    lineHeight: '1.45', letterSpacing: '0', textShadowIntensity: '0',
    cardShadow: 'medium', cardShadowColor: '#3b82f6', shadowOpacity: '0.10',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(59,130,246,0.12)',
    itemSpacing: '10', rowSpacing: '5', panelPadding: '14'
  },
  peach: {
    themePrimary: '#ec4899', themeAccent: '#8b5cf6',
    themeText: '#3d1a2a', themeBackground: '#fce7f0',
    themeOpacity: '0.45', themeRadius: '16',
    backdropBlur: '24', glowIntensity: '3',
    enableGradient: 'true', gradientEnd: '#f0d8e4', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'system-ui, -apple-system, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#be185d',
    overlayRequesterColor: '#9d174d',
    queueScrollSpeed: '80',
    lineHeight: '1.5', letterSpacing: '0', textShadowIntensity: '1',
    cardShadow: 'strong', cardShadowColor: '#ec4899', shadowOpacity: '0.18',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(236,72,153,0.15)',
    itemSpacing: '10', rowSpacing: '5', panelPadding: '14'
  },
  mint: {
    themePrimary: '#10b981', themeAccent: '#f59e0b',
    themeText: '#1a2d20', themeBackground: '#e6f2ea',
    themeOpacity: '0.42', themeRadius: '14',
    backdropBlur: '22', glowIntensity: '2',
    enableGradient: 'true', gradientEnd: '#d4e8da', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '700',
    overlaySongColor: '#065f46',
    overlayRequesterColor: '#64748b',
    queueScrollSpeed: '80',
    lineHeight: '1.45', letterSpacing: '0', textShadowIntensity: '0',
    cardShadow: 'medium', cardShadowColor: '#10b981', shadowOpacity: '0.10',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(16,185,129,0.12)',
    itemSpacing: '10', rowSpacing: '5', panelPadding: '14'
  },
  // === 深色系（暗色氛围毛玻璃） ===
  sakura: {
    themePrimary: '#ff7eb3', themeAccent: '#7ec8e3',
    themeText: '#fff5f7', themeBackground: '#1a1424',
    themeOpacity: '0.28', themeRadius: '16',
    backdropBlur: '22', glowIntensity: '6',
    enableGradient: 'true', gradientEnd: '#2d1a2e', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'system-ui, -apple-system, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#fda4af',
    overlayRequesterColor: '#c0a4b8',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.25',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(255,126,179,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  starry: {
    themePrimary: '#c4b5fd', themeAccent: '#67e8f9',
    themeText: '#f5f3ff', themeBackground: '#0f0a1e',
    themeOpacity: '0.26', themeRadius: '14',
    backdropBlur: '24', glowIntensity: '8',
    enableGradient: 'true', gradientEnd: '#1e1050', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '700',
    overlaySongColor: '#ddd6fe',
    overlayRequesterColor: '#a5b4fc',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '3',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.30',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(196,181,253,0.18)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  ocean: {
    themePrimary: '#60a5fa', themeAccent: '#fbbf24',
    themeText: '#f0f9ff', themeBackground: '#0c1929',
    themeOpacity: '0.30', themeRadius: '12',
    backdropBlur: '20', glowIntensity: '4',
    enableGradient: 'true', gradientEnd: '#061a34', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'Microsoft YaHei, SimHei, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#93c5fd',
    overlayRequesterColor: '#7b9cc4',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.22',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(96,165,250,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  sunset: {
    themePrimary: '#fb923c', themeAccent: '#f472b6',
    themeText: '#fffbf0', themeBackground: '#2a1508',
    themeOpacity: '0.30', themeRadius: '14',
    backdropBlur: '18', glowIntensity: '8',
    enableGradient: 'true', gradientEnd: '#3d1f0a', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'SimHei, Microsoft YaHei, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#fdba74',
    overlayRequesterColor: '#d6a074',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '3',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.28',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(251,146,60,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  cyber: {
    themePrimary: '#06b6d4', themeAccent: '#c084fc',
    themeText: '#f0f9ff', themeBackground: '#0a0a14',
    themeOpacity: '0.32', themeRadius: '6',
    backdropBlur: '14', glowIntensity: '16',
    enableGradient: 'true', gradientEnd: '#140a28', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#67e8f9',
    overlayRequesterColor: '#d8b4fe',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0.5', textShadowIntensity: '4',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.35',
    cardBorderWidth: '1', cardBorderColor: 'rgba(6,182,212,0.15)',
    panelBorderWidth: '1', panelBorderColor: 'rgba(6,182,212,0.25)',
    itemSpacing: '8', rowSpacing: '5', panelPadding: '14'
  },
  gold: {
    themePrimary: '#fbbf24', themeAccent: '#ef4444',
    themeText: '#fefce8', themeBackground: '#0c0a08',
    themeOpacity: '0.32', themeRadius: '10',
    backdropBlur: '22', glowIntensity: '8',
    enableGradient: 'true', gradientEnd: '#1c1608', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'KaiTi, STKaiti, serif',
    overlayFontWeight: '700',
    overlaySongColor: '#fde68a',
    overlayRequesterColor: '#a3a18a',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.28',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(251,191,36,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  lavender: {
    themePrimary: '#c084fc', themeAccent: '#f9a8d4',
    themeText: '#faf5ff', themeBackground: '#170f1f',
    themeOpacity: '0.28', themeRadius: '16',
    backdropBlur: '24', glowIntensity: '8',
    enableGradient: 'true', gradientEnd: '#2d1050', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'system-ui, -apple-system, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#e9d5ff',
    overlayRequesterColor: '#c4b5fd',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.25',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(192,132,252,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  // === 新增3种预设（v1.1.2） ===
  emerald: {
    themePrimary: '#34d399', themeAccent: '#fbbf24',
    themeText: '#f0fdf4', themeBackground: '#0a1a10',
    themeOpacity: '0.30', themeRadius: '12',
    backdropBlur: '20', glowIntensity: '5',
    enableGradient: 'true', gradientEnd: '#061208', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    overlayFontWeight: '700',
    overlaySongColor: '#6ee7b7',
    overlayRequesterColor: '#86a894',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.25',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(52,211,153,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
  rose: {
    themePrimary: '#f472b6', themeAccent: '#c084fc',
    themeText: '#fff1f5', themeBackground: '#1a0e14',
    themeOpacity: '0.30', themeRadius: '14',
    backdropBlur: '22', glowIntensity: '5',
    enableGradient: 'true', gradientEnd: '#2d1020', gradientAngle: '135',
    queueSongFontSize: '40', queueTitleFontSize: '30',
    overlayFontFamily: 'system-ui, -apple-system, sans-serif',
    overlayFontWeight: '800',
    overlaySongColor: '#f9a8d4',
    overlayRequesterColor: '#c4a0b0',
    queueScrollSpeed: '80',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', cardShadowColor: '#000000', shadowOpacity: '0.25',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(244,114,182,0.15)',
    itemSpacing: '9', rowSpacing: '5', panelPadding: '14'
  },
};

const classicPresetLabels = {
  // 极简
  pure: '⬜ 纯透极简',
  // 浅色系
  cream: '☕ 奶油杏白',
  sky: '☁️ 晴空浅蓝',
  mint: '🌿 薄荷浅绿',
  peach: '🍑 蜜桃奶白',
  // 深色系
  sakura: '🌸 樱粉甜梦',
  starry: '✨ 星夜幻紫',
  ocean: '🌊 深海湛蓝',
  sunset: '🌅 暖橘落日',
  gold: '👑 暗夜黑金',
  lavender: '💜 薰衣草雾',
  emerald: '🌲 翡翠深林',
  rose: '🌹 丝绒玫瑰',
  cyber: '🎆 赛博霓虹'
};

const classicPresetSwatches = {
  pure: ['#ffffff', '#555555', '#888888', '#1a1a1a'],
  cream: ['#f5ede4', '#f59e0b', '#d97706', '#2d1a08'],
  sky: ['#e8f2f8', '#3b82f6', '#f59e0b', '#1a2e3d'],
  peach: ['#fce7f0', '#ec4899', '#8b5cf6', '#3d1a2a'],
  mint: ['#e6f2ea', '#10b981', '#f59e0b', '#1a2d20'],
  sakura: ['#1a1424', '#ff7eb3', '#7ec8e3', '#fff5f7'],
  starry: ['#0f0a1e', '#c4b5fd', '#67e8f9', '#f5f3ff'],
  ocean: ['#0c1929', '#60a5fa', '#fbbf24', '#f0f9ff'],
  sunset: ['#2a1508', '#fb923c', '#f472b6', '#fffbf0'],
  cyber: ['#0a0a14', '#06b6d4', '#c084fc', '#f0f9ff'],
  gold: ['#0c0a08', '#fbbf24', '#ef4444', '#fefce8'],
  lavender: ['#170f1f', '#c084fc', '#f9a8d4', '#faf5ff'],
  emerald: ['#0a1a10', '#34d399', '#fbbf24', '#f0fdf4'],
  rose: ['#1a0e14', '#f472b6', '#c084fc', '#fff1f5']
};

const songBoardThemePresets = {
  pure: {
    songBoardThemePrimary: '#555555', songBoardThemeAccent: '#888888',
    songBoardThemeText: '#1a1a1a', songBoardThemeBackground: '#ffffff',
    songBoardThemeOpacity: '0.00', songBoardThemeRadius: '0',
    songBoardBackdropBlur: '0', songBoardGlowIntensity: '0',
    songBoardEnableGradient: 'false', songBoardGradientEnd: '#ffffff',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '600', songBoardSongColor: '#1a1a1a',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80',
    gradientAngle: '135',
    lineHeight: '1.5', letterSpacing: '0.5', textShadowIntensity: '0',
    cardShadow: 'none', shadowOpacity: '0',
    cardBorderWidth: '1', cardBorderColor: 'rgba(0,0,0,0.08)',
    panelBorderWidth: '0', panelBorderColor: '',
    itemSpacing: '12', rowSpacing: '6', panelPadding: '16'
  },
  sunset: {
    songBoardThemePrimary: '#fb923c', songBoardThemeAccent: '#f472b6',
    songBoardThemeText: '#fffbf0', songBoardThemeBackground: '#2a1508',
    songBoardThemeOpacity: '0.30', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '18', songBoardGlowIntensity: '6',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#3d1f0a',
    songBoardFontFamily: 'SimHei, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#fdba74',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '17', songBoardTitleFontSize: '15',
    scrollSeconds: '80',
    gradientAngle: '135',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '3',
    cardShadow: 'strong', shadowOpacity: '0.28',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(251,146,60,0.15)',
    itemSpacing: '9', rowSpacing: '6', panelPadding: '14'
  },
  starry: {
    songBoardThemePrimary: '#c4b5fd', songBoardThemeAccent: '#67e8f9',
    songBoardThemeText: '#f5f3ff', songBoardThemeBackground: '#0f0a1e',
    songBoardThemeOpacity: '0.26', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '24', songBoardGlowIntensity: '6',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#1e1050',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '700', songBoardSongColor: '#ddd6fe',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80',
    gradientAngle: '135',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '3',
    cardShadow: 'strong', shadowOpacity: '0.30',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(196,181,253,0.18)',
    itemSpacing: '9', rowSpacing: '6', panelPadding: '14'
  },
  ocean: {
    songBoardThemePrimary: '#60a5fa', songBoardThemeAccent: '#fbbf24',
    songBoardThemeText: '#f0f9ff', songBoardThemeBackground: '#0c1929',
    songBoardThemeOpacity: '0.30', songBoardThemeRadius: '12',
    songBoardBackdropBlur: '20', songBoardGlowIntensity: '4',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#061a34',
    songBoardFontFamily: 'Microsoft YaHei, SimHei, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#93c5fd',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80',
    gradientAngle: '135',
    lineHeight: '1.4', letterSpacing: '0', textShadowIntensity: '2',
    cardShadow: 'strong', shadowOpacity: '0.22',
    cardBorderWidth: '0', cardBorderColor: '',
    panelBorderWidth: '1', panelBorderColor: 'rgba(96,165,250,0.15)',
    itemSpacing: '9', rowSpacing: '6', panelPadding: '14'
  },
  sky: {
    songBoardThemePrimary: '#3b82f6', songBoardThemeAccent: '#f59e0b',
    songBoardThemeText: '#1a2e3d', songBoardThemeBackground: '#e8f2f8',
    songBoardThemeOpacity: '0.42', songBoardThemeRadius: '12',
    songBoardBackdropBlur: '22', songBoardGlowIntensity: '2',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#d8e8f4',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '700', songBoardSongColor: '#1e40af',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  mint: {
    songBoardThemePrimary: '#10b981', songBoardThemeAccent: '#f59e0b',
    songBoardThemeText: '#1a2d20', songBoardThemeBackground: '#e6f2ea',
    songBoardThemeOpacity: '0.42', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '22', songBoardGlowIntensity: '2',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#d4e8da',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '700', songBoardSongColor: '#065f46',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  peach: {
    songBoardThemePrimary: '#ec4899', songBoardThemeAccent: '#8b5cf6',
    songBoardThemeText: '#3d1a2a', songBoardThemeBackground: '#fce7f0',
    songBoardThemeOpacity: '0.45', songBoardThemeRadius: '16',
    songBoardBackdropBlur: '24', songBoardGlowIntensity: '3',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#f0d8e4',
    songBoardFontFamily: 'system-ui, -apple-system, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#be185d',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  emerald: {
    songBoardThemePrimary: '#34d399', songBoardThemeAccent: '#fbbf24',
    songBoardThemeText: '#f0fdf4', songBoardThemeBackground: '#0a1a10',
    songBoardThemeOpacity: '0.30', songBoardThemeRadius: '12',
    songBoardBackdropBlur: '20', songBoardGlowIntensity: '5',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#061208',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '700', songBoardSongColor: '#6ee7b7',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  rose: {
    songBoardThemePrimary: '#f472b6', songBoardThemeAccent: '#c084fc',
    songBoardThemeText: '#fff1f5', songBoardThemeBackground: '#1a0e14',
    songBoardThemeOpacity: '0.30', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '22', songBoardGlowIntensity: '5',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#2d1020',
    songBoardFontFamily: 'system-ui, -apple-system, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#f9a8d4',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },

  // === 新增5种预设（v1.3.3） ===
  terracotta: {
    songBoardThemePrimary: '#c67b5c', songBoardThemeAccent: '#8b9a6b',
    songBoardThemeText: '#3d2e26', songBoardThemeBackground: '#f5f0e8',
    songBoardThemeOpacity: '0.40', songBoardThemeRadius: '12',
    songBoardBackdropBlur: '16', songBoardGlowIntensity: '2',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#e8ddd0',
    songBoardFontFamily: 'KaiTi, STKaiti, serif',
    songBoardFontWeight: '700', songBoardSongColor: '#8b5a3c',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  coral: {
    songBoardThemePrimary: '#ff6b6b', songBoardThemeAccent: '#4ecdc4',
    songBoardThemeText: '#fff5f5', songBoardThemeBackground: '#1a2a2a',
    songBoardThemeOpacity: '0.32', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '20', songBoardGlowIntensity: '6',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#0d4040',
    songBoardFontFamily: 'Microsoft YaHei, SimHei, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#ffb3b3',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '17', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  ink: {
    songBoardThemePrimary: '#6b5b4f', songBoardThemeAccent: '#c41e3a',
    songBoardThemeText: '#2c2416', songBoardThemeBackground: '#f5f0e1',
    songBoardThemeOpacity: '0.38', songBoardThemeRadius: '8',
    songBoardBackdropBlur: '10', songBoardGlowIntensity: '0',
    songBoardEnableGradient: 'false', songBoardGradientEnd: '#f5f0e1',
    songBoardFontFamily: 'KaiTi, STKaiti, SimSun, serif',
    songBoardFontWeight: '600', songBoardSongColor: '#4a3728',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '16',
    scrollSeconds: '80'
  },
  slate: {
    songBoardThemePrimary: '#6b7b8d', songBoardThemeAccent: '#f0a500',
    songBoardThemeText: '#f5f7fa', songBoardThemeBackground: '#1e2328',
    songBoardThemeOpacity: '0.34', songBoardThemeRadius: '10',
    songBoardBackdropBlur: '18', songBoardGlowIntensity: '4',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#2a3038',
    songBoardFontFamily: 'PingFang SC, Microsoft YaHei, sans-serif',
    songBoardFontWeight: '700', songBoardSongColor: '#c0c8d4',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
  burgundy: {
    songBoardThemePrimary: '#a61e4d', songBoardThemeAccent: '#d4a574',
    songBoardThemeText: '#faf0f0', songBoardThemeBackground: '#1a1018',
    songBoardThemeOpacity: '0.28', songBoardThemeRadius: '14',
    songBoardBackdropBlur: '24', songBoardGlowIntensity: '5',
    songBoardEnableGradient: 'true', songBoardGradientEnd: '#2d1528',
    songBoardFontFamily: 'system-ui, -apple-system, sans-serif',
    songBoardFontWeight: '800', songBoardSongColor: '#e8b4b8',
    songBoardTitle: '可点歌单',
    songBoardSongFontSize: '16', songBoardTitleFontSize: '15',
    scrollSeconds: '80'
  },
};

const songBoardPresetLabels = {
  // 极简
  pure: '⬜ 纯透极简',
  // 深色系
  sunset: '🌅 暖橘落日',
  starry: '✨ 星夜幻紫',
  ocean: '🌊 深海湛蓝',
  emerald: '🌲 翡翠深林',
  rose: '🌹 丝绒玫瑰',
  burgundy: '🍷 勃艮第醇',
  coral: '🐠 珊瑚海礁',
  slate: '⚙️ 工业灰调',
  // 浅色系
  sky: '☁️ 晴空浅蓝',
  mint: '🌿 薄荷浅绿',
  peach: '🍑 蜜桃奶白',
  terracotta: '🏺 陶土侘寂',
  ink: '🖋 墨香宣纸'
};

const songBoardPresetSwatches = {
  pure: ['#ffffff', '#555555', '#888888', '#1a1a1a'],
  sunset: ['#2a1508', '#fb923c', '#f472b6', '#fffbf0'],
  starry: ['#0f0a1e', '#c4b5fd', '#67e8f9', '#f5f3ff'],
  ocean: ['#0c1929', '#60a5fa', '#fbbf24', '#f0f9ff'],
  sky: ['#e8f2f8', '#3b82f6', '#f59e0b', '#1a2e3d'],
  mint: ['#e6f2ea', '#10b981', '#f59e0b', '#1a2d20'],
  peach: ['#fce7f0', '#ec4899', '#8b5cf6', '#3d1a2a'],
  emerald: ['#0a1a10', '#34d399', '#fbbf24', '#f0fdf4'],
  rose: ['#1a0e14', '#f472b6', '#c084fc', '#fff1f5'],
  terracotta: ['#f5f0e8', '#c67b5c', '#8b9a6b', '#3d2e26'],
  coral: ['#1a2a2a', '#ff6b6b', '#4ecdc4', '#fff5f5'],
  ink: ['#f5f0e1', '#6b5b4f', '#c41e3a', '#2c2416'],
  slate: ['#1e2328', '#6b7b8d', '#f0a500', '#f5f7fa'],
  burgundy: ['#1a1018', '#a61e4d', '#d4a574', '#faf0f0']
};

  window.AdminApp = window.AdminApp || {};
  window.AdminApp.theme = {
    defaultThemeLook,
    classicThemePresets,
    classicPresetLabels,
    classicPresetSwatches,
    songBoardThemePresets,
    songBoardPresetLabels,
    songBoardPresetSwatches
  };
})();
